spring:
  datasource:
    url: jdbc:mysql://localhost:3307/food_app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
